// This query returns all file creation events where the filename ends with ".encrypted".
// It is useful for identifying files that have been encrypted by ransomware.
FileCreationEvents
| where filename endswith ".encrypted"
| count

// This query returns the number of unique hostnames where encrypted files were created.
// It helps in identifying the scope of the ransomware infection across different hosts.
FileCreationEvents
| where filename endswith ".encrypted"
| distinct hostname 

// A randsome note was left on at least one of the infected hosts. 
// This query returns all file creation events where the filename is "We_Have_Your_Data_Pay_Up.txt".
// We identify the Sha256 hash of the ransom note and use it to find all other instances of the same file across the environment.
// 97c348e95c8a8aeb8808f76434d73a92bbcb6b4586788365762b22624990b018
FileCreationEvents
| where filename == "We_Have_Your_Data_Pay_Up.txt"

//ProcessEvents tell us what kinds of things happened on a computer.
ProcessEvents
| where hostname == "AMFB-MACHINE"
| where timestamp between (datetime(2024-06-17) ..  datetime(2024-06-18))

OutboundNetworkEvents
| where url has "patient_data_exporter.exe"

// We can use this domain to find more websites or servers that the hacker controls.
PassiveDns
| where domain == "secure-health-access.com"

PassiveDns
| where ip in ("203.0.113.1", "203.0.113.2")

// We can see what kind of reconnaissance the hackers did on the network 
// by looking for any connections to the IP addresses that we found in the PassiveDns query.
InboundNetworkEvents
| where src_ip  in ("203.0.113.1", "203.0.113.2")
| where url has "bypass"

InboundNetworkEvents
| where src_ip  in ("203.0.113.1", "203.0.113.2")
| where url has "patient"

// We are looking for any account the hackers may have logged into on the network. 
// We can use the IP addresses we found in the PassiveDns query to find any authentication events that may have occurred from those IP addresses.
AuthenticationEvents
| where src_ip  in ("203.0.113.1", "203.0.113.2")

// We are looking  for the account owner the hackers used to log into the network.
Employees
| where  username == "andavis"

// We are seeing how many requests were made to the fake website
OutboundNetworkEvents
| where url has "raisinkanes.com"

// We are looking for the IP addresses that made requests to the fake website.
OutboundNetworkEvents
| where url has "raisinkanes.com"
| distinct src_ip

// We are searching for common files this ip forced to be downloaded from the fake website.
let host_that_clicked = 
Employees
| where ip_addr  in ("10.10.0.231","10.10.0.151","10.10.0.42")
|distinct hostname;
FileCreationEvents
| where hostname in (host_that_clicked)

FileCreationEvents
| where filename == "Raisin_Kane_Promo_Offer.docx"

ProcessEvents
| where hostname == "RQJQ-MACHINE"
| where timestamp between (datetime(2024-05-01) .. datetime(2024-05-02))

// Figuring out when the attacker used Cobalt Strike to move laterally through the network.
// specifically Anthony Davis's machine. We can see that the attacker used Cobalt Strike to move laterally through the network.
ProcessEvents
| where hostname == "AMFB-MACHINE"
| where process_commandline contains "cobalt"
//2024-05-14 12:24:45+00:00

